import crypto from 'node:crypto';

export const STATES = Object.freeze(['CREATED','INSPECTING','CONTRACTING','CONTRACT_READY','EPISTEMIC_PLANNING','EPISTEMIC_READY','ROUTED','AUTHORIZED','EXECUTING','OBSERVING','INTEGRATING','CHALLENGING','VERIFYING','VALIDATING','AUDITING','CALIBRATING','RELEASE_ELIGIBLE','RELEASED','CONTRACT_BLOCKED','AUTHORITY_BLOCKED','DEPENDENCY_BLOCKED','INTERFACE_REJECTED','EVIDENCE_INSUFFICIENT','TOOL_UNAVAILABLE','EXECUTION_FAILED','CORRECTION_REQUIRED','VERIFICATION_FAILED','VALIDATION_FAILED','AUDIT_FAILED','ABSTAINED','ESCALATED','WITHHELD','TERMINATED']);
export const ACK = Object.freeze(['ACK_ACCEPTED','ACK_ACCEPTED_WITH_QUALIFICATION','ACK_REJECTED_SCHEMA','ACK_REJECTED_AUTHORITY','ACK_REJECTED_EVIDENCE','ACK_REJECTED_DEPENDENCY','ACK_REJECTED_STATE','ACK_DEFERRED','ACK_ESCALATED']);
export const ROLE = Object.freeze({KERNEL:'architectural_authority',CORE:'capability_interface',MASTER:'methodological_execution',VLF:'textual_transformation',TEXT_METRICS:'measurement'});
export const sha256 = value => crypto.createHash('sha256').update(typeof value === 'string' ? value : canonical(value)).digest('hex');
export function canonical(value){if(Array.isArray(value))return '['+value.map(canonical).join(',')+']';if(value&&typeof value==='object')return '{'+Object.keys(value).sort().map(k=>JSON.stringify(k)+':'+canonical(value[k])).join(',')+'}';return JSON.stringify(value);}
export function validateCapability(profile){const required=['capability_family','capability_id','version','schema_version','declared_capabilities','authority_boundary','input_schema','output_schema','semantic_guarantees','limitations','provenance','compatibility_profile'];const missing=required.filter(k=>!(k in (profile||{})));return {valid:missing.length===0,missing};}
export function compatible(required,offered){const a=validateCapability(offered);if(!a.valid)return {compatible:false,reason:'SCHEMA'};const keys=['schema','semantic','authority','failure','provenance'];const checks=Object.fromEntries(keys.map(k=>[k,Boolean(offered.compatibility_profile?.[k])]));return {compatible:Object.values(checks).every(Boolean),checks,reason:Object.values(checks).every(Boolean)?'PASS':'PROFILE'};}
export function handoff(record){const required=['handoff_id','task_id','execution_id','contract_revision','sender_authority','receiver_authority','object_id','revision','payload_type','input_schema','output_schema','preconditions','postconditions','dependencies','evidence_references','provenance_references','expected_ack_type','next_authorized_state','trace_id'];const missing=required.filter(k=>!(k in (record||{})));if(missing.length)return {commit:false,ack:'ACK_REJECTED_SCHEMA',missing};if(record.revision_status==='STALE')return {commit:false,ack:'ACK_REJECTED_STATE'};if(record.authority_valid===false)return {commit:false,ack:'ACK_REJECTED_AUTHORITY'};if(record.dependencies_satisfied===false)return {commit:false,ack:'ACK_REJECTED_DEPENDENCY'};if(record.evidence_disposition_valid===false)return {commit:false,ack:'ACK_REJECTED_EVIDENCE'};return {commit:true,ack:record.qualified?'ACK_ACCEPTED_WITH_QUALIFICATION':'ACK_ACCEPTED',state:record.next_authorized_state};}
export function releaseGate(g={}){const inherited=['contract_satisfied','epistemic_specification_satisfied','authorized_execution','dependencies_closed','material_handoffs_acknowledged','evidence_disposition_complete','provenance_disposition_complete','verification_pass','validation_pass','red_team_complete','uncertainty_calibrated','audit_pass','capability_boundaries_preserved','no_unresolved_release_blocker'];const ultimate=['policy_compilation_valid_or_na','constraint_plan_valid_or_na','temporal_monitor_clear','metamorphic_disposition_complete_or_na','merkle_valid_or_na','signed_attestation_valid_or_na','transparency_log_valid_or_na','execution_attestation_honest','assurance_budget_acceptable','control_conflicts_resolved','assurance_orthogonality_acceptable','shadow_promotion_satisfied','ultimate_regression_pass','no_ultimate_release_blocker'];const failed=[...inherited,...ultimate].filter(k=>g[k]!==true);return {eligible:failed.length===0,state:failed.length?'WITHHELD':'RELEASE_ELIGIBLE',failed};}
export function temporal(events){const names=events.map(e=>e.event),violations=[];const released=names.indexOf('RELEASED'),eligible=names.indexOf('RELEASE_ELIGIBLE');if(released>=0&&(eligible<0||eligible>released))violations.push('RELEASE_ORDER');for(const [i,e] of events.entries())if(e.event==='HANDOFF_COMMITTED'&&!events.slice(0,i).some(x=>x.event==='VALID_ACK'&&x.handoff_id===e.handoff_id))violations.push('HANDOFF_ACK_ORDER');for(const [i,e] of events.entries())if(e.event==='PARALLEL_EXECUTION_CLAIM'&&!events.slice(0,i+1).some(x=>x.event==='OBSERVED_RUNTIME_SUPPORT'))violations.push('FALSE_PARALLEL_CLAIM');return {pass:violations.length===0,violations};}
export function merkle(leaves){if(!leaves.length)return sha256('');let level=leaves.map(x=>sha256(x));while(level.length>1){const next=[];for(let i=0;i<level.length;i+=2){const a=level[i],b=level[i+1]||a;next.push(sha256(a+b));}level=next;}return level[0];}
export function signManifest(manifest){const {publicKey,privateKey}=crypto.generateKeyPairSync('ed25519');const body=Buffer.from(canonical(manifest));const signature=crypto.sign(null,body,privateKey).toString('base64');const valid=crypto.verify(null,body,publicKey,Buffer.from(signature,'base64'));return {algorithm:'ed25519',manifest_hash:sha256(body),signature,valid,note:'VALID_SIGNATURE != CLAIM_TRUE'};}
export function executionAttestation(stages){const order=['SOURCE_VERIFIED','BUILD_VERIFIED','ARTIFACT_VERIFIED','CONFIGURATION_VERIFIED','DEPLOYMENT_VERIFIED','RUNTIME_OBSERVED','EXECUTION_OBSERVED','RESULT_BOUND_TO_EXECUTION'];let highest=-1;for(const s of stages){const i=order.indexOf(s);if(i<0||i>highest+1)return {valid:false,highest:order[highest]??null,reason:'CHAIN_GAP'};highest=i;}return {valid:true,highest:order[highest]??null,complete:highest===order.length-1};}
export function metamorphicOrderInvariant(fn,input){const a=fn(input),b=fn([...input].reverse());return {pass:canonical(a)===canonical(b),a,b};}
export function policyCompile(policy){const required=['policy_id','authority','scope','predicate','failure','precedence'];const missing=required.filter(k=>!(k in (policy||{})));if(missing.length)return {status:'AMBIGUOUS',missing};if(policy.authority!=='KERNEL'&&policy.can_release===true)return {status:'AUTHORITY_EXPANSION_BLOCKED'};return {status:'COMPILED',ir:{...policy,compiled:true}};}
export function plan({operations=[],dependencies=[]}={}){const ids=new Set(operations),bad=dependencies.filter(([a,b])=>!ids.has(a)||!ids.has(b));if(bad.length)return {status:'UNSAT',unsat_core:bad};const indeg=Object.fromEntries(operations.map(x=>[x,0])),out=Object.fromEntries(operations.map(x=>[x,[]]));for(const [a,b] of dependencies){out[a].push(b);indeg[b]++;}const q=operations.filter(x=>indeg[x]===0),order=[];while(q.length){const n=q.shift();order.push(n);for(const m of out[n])if(--indeg[m]===0)q.push(m);}return order.length===operations.length?{status:'SAT',order}:{status:'UNSAT',unsat_core:['CYCLE']};}
export function claimBound({claim_strength,evidence_strength}){return {pass:claim_strength<=evidence_strength,maximum:evidence_strength};}
